import { BlockType, BlockDefinition } from './types';

export const BLOCK_DEFS: Record<BlockType, BlockDefinition> = {
  [BlockType.AIR]: {
    id: BlockType.AIR,
    nameEn: 'Air',
    nameNl: 'Lucht',
    hardness: 0,
    sound: 'dirt',
    isTransparent: true,
    isSolid: false,
    category: 'natural',
  },
  [BlockType.GRASS]: {
    id: BlockType.GRASS,
    nameEn: 'Grass Block',
    nameNl: 'Grasblok',
    hardness: 0.6,
    sound: 'grass',
    category: 'natural',
  },
  [BlockType.DIRT]: {
    id: BlockType.DIRT,
    nameEn: 'Dirt',
    nameNl: 'Aarde',
    hardness: 0.5,
    sound: 'dirt',
    category: 'natural',
  },
  [BlockType.STONE]: {
    id: BlockType.STONE,
    nameEn: 'Stone',
    nameNl: 'Steen',
    hardness: 1.5,
    sound: 'stone',
    category: 'building',
  },
  [BlockType.COBBLESTONE]: {
    id: BlockType.COBBLESTONE,
    nameEn: 'Cobblestone',
    nameNl: 'Keisteen',
    hardness: 2.0,
    sound: 'stone',
    category: 'building',
  },
  [BlockType.WOOD_LOG]: {
    id: BlockType.WOOD_LOG,
    nameEn: 'Oak Log',
    nameNl: 'Eikenhout Stam',
    hardness: 2.0,
    sound: 'wood',
    category: 'natural',
  },
  [BlockType.WOOD_PLANKS]: {
    id: BlockType.WOOD_PLANKS,
    nameEn: 'Oak Planks',
    nameNl: 'Eikenhouten Planken',
    hardness: 1.5,
    sound: 'wood',
    category: 'building',
  },
  [BlockType.LEAVES]: {
    id: BlockType.LEAVES,
    nameEn: 'Oak Leaves',
    nameNl: 'Eikenbladeren',
    hardness: 0.2,
    sound: 'grass',
    isTransparent: true,
    category: 'natural',
  },
  [BlockType.BEDROCK]: {
    id: BlockType.BEDROCK,
    nameEn: 'Bedrock',
    nameNl: 'Bodemsteen',
    hardness: -1, // unbreakable in survival
    sound: 'stone',
    category: 'building',
  },
  [BlockType.SAND]: {
    id: BlockType.SAND,
    nameEn: 'Sand',
    nameNl: 'Zand',
    hardness: 0.5,
    sound: 'sand',
    category: 'natural',
  },
  [BlockType.GLASS]: {
    id: BlockType.GLASS,
    nameEn: 'Glass',
    nameNl: 'Glas',
    hardness: 0.3,
    sound: 'glass',
    isTransparent: true,
    category: 'building',
  },
  [BlockType.BRICK]: {
    id: BlockType.BRICK,
    nameEn: 'Bricks',
    nameNl: 'Bakstenen',
    hardness: 2.0,
    sound: 'stone',
    category: 'building',
  },
  [BlockType.TNT]: {
    id: BlockType.TNT,
    nameEn: 'TNT',
    nameNl: 'TNT',
    hardness: 0.0,
    sound: 'grass',
    category: 'functional',
  },
  [BlockType.CRAFTING_TABLE]: {
    id: BlockType.CRAFTING_TABLE,
    nameEn: 'Crafting Table',
    nameNl: 'Werkbank',
    hardness: 2.0,
    sound: 'wood',
    category: 'functional',
  },
  [BlockType.FURNACE]: {
    id: BlockType.FURNACE,
    nameEn: 'Furnace',
    nameNl: 'Oven',
    hardness: 3.0,
    sound: 'stone',
    category: 'functional',
  },
  [BlockType.CHEST]: {
    id: BlockType.CHEST,
    nameEn: 'Chest',
    nameNl: 'Kist',
    hardness: 2.0,
    sound: 'wood',
    category: 'functional',
  },
  [BlockType.BOOKSHELF]: {
    id: BlockType.BOOKSHELF,
    nameEn: 'Bookshelf',
    nameNl: 'Boekenkast',
    hardness: 1.5,
    sound: 'wood',
    category: 'building',
  },
  [BlockType.COAL_ORE]: {
    id: BlockType.COAL_ORE,
    nameEn: 'Coal Ore',
    nameNl: 'Steenkoolerts',
    hardness: 3.0,
    sound: 'stone',
    category: 'ores',
  },
  [BlockType.IRON_ORE]: {
    id: BlockType.IRON_ORE,
    nameEn: 'Iron Ore',
    nameNl: 'IJzererts',
    hardness: 3.0,
    sound: 'stone',
    category: 'ores',
  },
  [BlockType.GOLD_ORE]: {
    id: BlockType.GOLD_ORE,
    nameEn: 'Gold Ore',
    nameNl: 'Gouderts',
    hardness: 3.0,
    sound: 'stone',
    category: 'ores',
  },
  [BlockType.DIAMOND_ORE]: {
    id: BlockType.DIAMOND_ORE,
    nameEn: 'Diamond Ore',
    nameNl: 'Diamanterts',
    hardness: 3.5,
    sound: 'stone',
    category: 'ores',
  },
  [BlockType.EMERALD_ORE]: {
    id: BlockType.EMERALD_ORE,
    nameEn: 'Emerald Ore',
    nameNl: 'Smaragderts',
    hardness: 3.5,
    sound: 'stone',
    category: 'ores',
  },
  [BlockType.GLOWSTONE]: {
    id: BlockType.GLOWSTONE,
    nameEn: 'Glowstone',
    nameNl: 'Gloeisteen',
    hardness: 0.3,
    sound: 'glass',
    lightLevel: 15,
    category: 'building',
  },
  [BlockType.OBSIDIAN]: {
    id: BlockType.OBSIDIAN,
    nameEn: 'Obsidian',
    nameNl: 'Obsidiaan',
    hardness: 8.0,
    sound: 'stone',
    category: 'building',
  },
  [BlockType.WATER]: {
    id: BlockType.WATER,
    nameEn: 'Water',
    nameNl: 'Water',
    hardness: 100,
    sound: 'grass',
    isTransparent: true,
    isSolid: false,
    category: 'natural',
  },
  [BlockType.TORCH]: {
    id: BlockType.TORCH,
    nameEn: 'Torch',
    nameNl: 'Fakkel',
    hardness: 0.0,
    sound: 'wood',
    isTransparent: true,
    isSolid: false,
    lightLevel: 14,
    category: 'functional',
  },
  [BlockType.POPPY]: {
    id: BlockType.POPPY,
    nameEn: 'Poppy',
    nameNl: 'Klaproos',
    hardness: 0.0,
    sound: 'grass',
    isTransparent: true,
    isSolid: false,
    category: 'decorative',
  },
  [BlockType.DANDELION]: {
    id: BlockType.DANDELION,
    nameEn: 'Dandelion',
    nameNl: 'Paardenbloem',
    hardness: 0.0,
    sound: 'grass',
    isTransparent: true,
    isSolid: false,
    category: 'decorative',
  },
  [BlockType.SNOW]: {
    id: BlockType.SNOW,
    nameEn: 'Snow Block',
    nameNl: 'Sneeuwblok',
    hardness: 0.2,
    sound: 'grass',
    category: 'natural',
  },
  [BlockType.ICE]: {
    id: BlockType.ICE,
    nameEn: 'Ice',
    nameNl: 'IJs',
    hardness: 0.5,
    sound: 'glass',
    isTransparent: true,
    category: 'natural',
  },
  [BlockType.DIAMOND_SWORD]: {
    id: BlockType.DIAMOND_SWORD,
    nameEn: 'Diamond Sword',
    nameNl: 'Diamanten Zwaard',
    hardness: 0.0,
    sound: 'metal',
    isTransparent: true,
    isSolid: false,
    category: 'functional',
  },
  [BlockType.COOKED_BEEF]: {
    id: BlockType.COOKED_BEEF,
    nameEn: 'Cooked Beef',
    nameNl: 'Biefstuk (Eten)',
    hardness: 0.0,
    sound: 'grass',
    isTransparent: true,
    isSolid: false,
    category: 'functional',
  },
};

export const CREATIVE_BLOCKS: BlockType[] = [
  BlockType.DIAMOND_SWORD,
  BlockType.COOKED_BEEF,
  BlockType.GRASS,
  BlockType.DIRT,
  BlockType.STONE,
  BlockType.COBBLESTONE,
  BlockType.WOOD_LOG,
  BlockType.WOOD_PLANKS,
  BlockType.LEAVES,
  BlockType.BRICK,
  BlockType.SAND,
  BlockType.GLASS,
  BlockType.BOOKSHELF,
  BlockType.GLOWSTONE,
  BlockType.OBSIDIAN,
  BlockType.COAL_ORE,
  BlockType.IRON_ORE,
  BlockType.GOLD_ORE,
  BlockType.DIAMOND_ORE,
  BlockType.EMERALD_ORE,
  BlockType.CRAFTING_TABLE,
  BlockType.FURNACE,
  BlockType.CHEST,
  BlockType.TNT,
  BlockType.TORCH,
  BlockType.POPPY,
  BlockType.DANDELION,
  BlockType.SNOW,
  BlockType.ICE,
  BlockType.BEDROCK,
];
